from setuptools import setup

setup(
    name='otomasyon',
    version='',
    packages=['venviroment.lib.python3.7.site-packages.w3lib', 'venviroment.lib.python3.7.site-packages.parsel',
              'venviroment.lib.python3.7.site-packages.scrapy', 'venviroment.lib.python3.7.site-packages.scrapy.core',
              'venviroment.lib.python3.7.site-packages.scrapy.core.downloader',
              'venviroment.lib.python3.7.site-packages.scrapy.core.downloader.handlers',
              'venviroment.lib.python3.7.site-packages.scrapy.http',
              'venviroment.lib.python3.7.site-packages.scrapy.http.request',
              'venviroment.lib.python3.7.site-packages.scrapy.http.response',
              'venviroment.lib.python3.7.site-packages.scrapy.xlib',
              'venviroment.lib.python3.7.site-packages.scrapy.utils',
              'venviroment.lib.python3.7.site-packages.scrapy.loader',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib.loader',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib.spiders',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib.exporter',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib.pipeline',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib.linkextractors',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib.spidermiddleware',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib.downloadermiddleware',
              'venviroment.lib.python3.7.site-packages.scrapy.spiders',
              'venviroment.lib.python3.7.site-packages.scrapy.commands',
              'venviroment.lib.python3.7.site-packages.scrapy.selector',
              'venviroment.lib.python3.7.site-packages.scrapy.settings',
              'venviroment.lib.python3.7.site-packages.scrapy.contracts',
              'venviroment.lib.python3.7.site-packages.scrapy.pipelines',
              'venviroment.lib.python3.7.site-packages.scrapy.templates.project.module',
              'venviroment.lib.python3.7.site-packages.scrapy.templates.project.module.spiders',
              'venviroment.lib.python3.7.site-packages.scrapy.extensions',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib_exp',
              'venviroment.lib.python3.7.site-packages.scrapy.contrib_exp.downloadermiddleware',
              'venviroment.lib.python3.7.site-packages.scrapy.linkextractors',
              'venviroment.lib.python3.7.site-packages.scrapy.spidermiddlewares',
              'venviroment.lib.python3.7.site-packages.scrapy.downloadermiddlewares',
              'venviroment.lib.python3.7.site-packages.coverage', 'venviroment.lib.python3.7.site-packages.queuelib',
              'venviroment.lib.python3.7.site-packages.queuelib.tests',
              'venviroment.lib.python3.7.site-packages.cssselect', 'venviroment.lib.python3.7.site-packages.pydispatch',
              'venviroment.lib.python3.7.site-packages.pytest_cov'],
    url='',
    license='',
    author='atessu',
    author_email='',
    description=''
)
